run:
  task: reem
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 1
  batch_size_train: 32
  batch_size_eval: 4
  num_workers: 4
  warmup_steps: 5000
  seed: 42
  output_dir: "output/train"
  amp: True
  resume_ckpt_path: null
  evaluate: False
  eval_dataset_name: "vg_reg"
  load_ckpt_path: null
  report_metric: True
  visualize: True
  train_splits: ["train"]
  valid_splits: ["val"]
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True