base: ["configs/base/runs/eval.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/vg/vg1.0.yaml",
]

run:
  batch_size_eval: 4
  output_dir: "output/eval/vg1.0"
  eval_dataset_name: "vg1.0"
  #  load_ckpt_path: "output/train/union_reem/20240109064/checkpoint_0.pth" # [vg METEOR 19.85 CIDEr 165.2]
  load_ckpt_path: "/media/Disk1/ZhaoYuzhong/zhaoyuzhong/zyz/code/Reem/output/train/controlcap2_union_5e/20240302013/checkpoint_4.pth" # 42.0