base: ["configs/base/runs/eval.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/vg/vg1.2.yaml",
]

run:
  batch_size_eval: 1
  output_dir: "output/eval/vg1.2"
  eval_dataset_name: "vg1.2"
  load_ckpt_path: "ckpts/checkpoint_4.pth"