base: ["configs/base/runs/eval.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/vg/vg1.3.yaml",
]

run:
  batch_size_eval: 4
  output_dir: "output/eval/vg1.2"
  eval_dataset_name: "vg1.3"
#  load_ckpt_path: "/media/Disk1/ZhaoYuzhong/zhaoyuzhong/zyz/code/Reem/output/train/controlcap_union_5e/20240229235/checkpoint_4.pth" # otag
  load_ckpt_path: "/media/Disk1/ZhaoYuzhong/zhaoyuzhong/zyz/code/Reem/output/train/controlcap2_union_5e/20240302013/checkpoint_3.pth" # 42.0
#  load_ckpt_path: "/media/Disk1/ZhaoYuzhong/zhaoyuzhong/zyz/code/Reem/output/train/controlcap2_union_5e/20240303055/checkpoint_0.pth" # nouse