datasets:
  vg1.0:
    vis_processor:
      train:
        name: "reem"
        image_size: 224
      eval:
        name: "reem"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
    build_info:
      with_seg: False
      max_imgs: 1e7
      max_objs: 1e7
      obj_lvl: True
      cap_type: [ "grit" ]
      tag_list: "reem/commom/tag_parser/ram_tag_list.txt"
      annotations:
        train: [ ]
        val: [ "data/vg/annotations/rrecog/vg1.0/grit/test_grit.json" ]