base: ["configs/base/runs/train.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/vg/vgcoco.yaml",
]

model:
  finetune_llm: False
#  first_word_control: True
  tag_thr: 0.8

run:
  batch_size_train: 2
  max_epoch: 5
  output_dir: "output/train/vgcoco_5e"
  eval_dataset_name: "vgcoco"
