datasets:
  vg_reg:
    vis_processor:
      train:
        name: "controlcap"
        image_size: 224
      eval:
        name: "controlcap"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
      eval:
        name: "blip_caption"
    build_info:
      with_seg: False
      max_imgs: 1e7
      max_objs: 1e7
      obj_lvl: True
      cap_type: [ "dense" ]
      tag_list: "controlcap/common/tagging/ram_tag_list.txt"
      annotations:
        train: [ ]
        val: [ "data/vg/controlcap/vg_reg/test.json" ]