base: ["configs/base/runs/eval.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/vg_pred_bboxes/vg1.2.yaml",
]

run:
  batch_size_eval: 2
  output_dir: "output/eval/vg1.2_grit"
  eval_dataset_name: "vg1.2"
  load_ckpt_path: "/media/Disk1/ZhaoYuzhong/zhaoyuzhong/zyz/code/Reem/output/train/controlcap2_union_5e/20240302013/checkpoint_4.pth" # 42.0
