base: ["configs/base/runs/train.yaml",
       "configs/base/models/controlcap_flant5xl.yaml",
       "configs/base/datasets/refcoco/refcocog.yaml",
       "configs/base/datasets/vg/vg1.2.yaml",
       "configs/base/datasets/vg/vg_reg.yaml"
]

model:
  finetune_llm: False
  first_word_control: False
  tag_thr: 0.7

run:
  batch_size_train: 64
  max_epoch: 5
  output_dir: "output/train/vg_refcocog_5e"
  eval_dataset_name: "vg1.2"


