model:
  arch: reem_t5
  load_finetuned: False
  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xl.pth"
  finetuned: ""
  finetune_llm: False
  first_word_control: False

  # vit encoder
#  max_txt_len: 32
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # T5
  t5_model: "google/flan-t5-xl"

  prompt: "a photo of"